# CMake generated Testfile for 
# Source directory: /home/li/workspace/msv/tangyuanrobot/libopendavinci
# Build directory: /home/li/workspace/msv/tangyuanrobot/libopendavinci
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(ZipTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ZipTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ZipTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(MutexTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/MutexTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(MutexTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(RunnerTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/RunnerTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(RunnerTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(StringProtocolTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/StringProtocolTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(StringProtocolTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(RuntimeControlContainerMultipleAppsTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/RuntimeControlContainerMultipleAppsTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(RuntimeControlContainerMultipleAppsTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(KeyValueConfigurationTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/KeyValueConfigurationTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(KeyValueConfigurationTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(StringToolboxTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/StringToolboxTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(StringToolboxTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ServiceTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ServiceTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ServiceTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ClockTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ClockTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ClockTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(RuntimeControlTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/RuntimeControlTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(RuntimeControlTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(PulseAckContainersMessageTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/PulseAckContainersMessageTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(PulseAckContainersMessageTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ControlFlowTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ControlFlowTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ControlFlowTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(NetstringsProtocolTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/NetstringsProtocolTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(NetstringsProtocolTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(SerializationTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/SerializationTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(SerializationTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(TreeNodeTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/TreeNodeTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(TreeNodeTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(DMCPConnectionTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/DMCPConnectionTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(DMCPConnectionTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(DMCPDiscovererTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/DMCPDiscovererTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(DMCPDiscovererTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(AbstractCIDModuleTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/AbstractCIDModuleTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(AbstractCIDModuleTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(SharedMemoryTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/SharedMemoryTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(SharedMemoryTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(SharedPointerTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/SharedPointerTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(SharedPointerTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ConferenceFactoryTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ConferenceFactoryTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ConferenceFactoryTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(QueueTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/QueueTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(QueueTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(TCPTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/TCPTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(TCPTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(DataStoreTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/DataStoreTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(DataStoreTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(DisposalTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/DisposalTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(DisposalTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ConferenceClientModuleTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ConferenceClientModuleTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ConferenceClientModuleTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(RuntimeControlContainerTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/RuntimeControlContainerTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(RuntimeControlContainerTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(FalseSerializationTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/FalseSerializationTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(FalseSerializationTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(TimeStampTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/TimeStampTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(TimeStampTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ConditionTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ConditionTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ConditionTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(CommandLineParserTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/CommandLineParserTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(CommandLineParserTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(UDPTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/UDPTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(UDPTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(TimeFactoryTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/TimeFactoryTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(TimeFactoryTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ConnectionTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ConnectionTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ConnectionTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
ADD_TEST(ContainerTestSuite.h-TestSuite "/home/li/workspace/msv/tangyuanrobot/libopendavinci/ContainerTestSuite.h-TestSuite")
SET_TESTS_PROPERTIES(ContainerTestSuite.h-TestSuite PROPERTIES  TIMEOUT "1800")
